### ISSUE TITLE
Channel Integration Guide Clarity

### ISSUE THREAD

**Issue by Coobers** [LinnSystems/LinnworksNetSDK#10]
We would like to point out unclear situation with Channel Integration Guide (https://github.com/LinnSystems/LinnworksNetSDK/blob/master/Linnworks/Example%20Applications/SampleChannel/Channel%20Integration%20Endpoint%20Guide.pdf).

Returns in Prices and Despatch do not clearly indicate that list of items that were successfully processed should be returned with information about lack of Error in form of:
`{
"Error": null,
"Products": [{
"Error": null",
"SKU": "SKUOfProductEverythingFine" }]
} `

Please confirm if such behavior is a good one.

**Comment by LinnSystems** [comment]
Hi @Coobers,

I can confirm that the process should work in the way that you have suggested. Each item should be returned that has been updated with a blank error if no error has occurred whilst updating the item.

I will get this updated to reflect this and it should be available shortly.
