### ISSUE TITLE
Dates don't format correctly

### ISSUE THREAD

**Issue by wizzardmr42** [LinnSystems/LinnworksNetSDK#11]
Json object dates aren't formatted correctly so cause errors in API calls and URL param dates aren't formatted at all so get converted using the system default date format by the DateTime.ToString() function.

**Comment by LinnSystems** [comment]
Hi @wizzardmr42 

We currently have a change that is in QA to resolve this, and it should be available shortly should there be no issues with the testing.

**Comment by LinnSystems** [comment]
Hi @wizzardmr42 

We have updated the latest version to have changes that have been suggested by you.

Thanks for the suggestions.
