### ISSUE TITLE
.NET: Base classes/interfaces for standard patterns

### ISSUE THREAD

**Issue by wizzardmr42** [LinnSystems/LinnworksNetSDK#13]
Several classes have common elements eg. a Name and Guid property.  It would make sense to have a base class/interface where possible to make it easier for developers to reuse code that consumes these objects

**Comment by LinnSystems** [comment]
Hi @wizzardmr42 

As I have stated in your other request, the code provided for the SDK is generated automatically. Your request, although feasible in an environment where the code does not need to be generated automatically, would require a large amount of work to implement said features. 

There is lots of functionality in the API, and in the SDK, and the collision of field names over items is fairly trivial for us to warrant a restructure to the way that the code is generated. 

For now, I will have to close this issue as it will not be achievable in the way that the code is currently generated.
