### ISSUE TITLE
Issues with channel integration

### ISSUE THREAD

**Issue by wjbLabs** [LinnSystems/LinnworksNetSDK#14]
I carefully followed [.pdf guide](https://github.com/LinnSystems/LinnworksNetSDK/blob/master/Linnworks/Example%20Applications/SampleChannel/Channel%20Integration%20Endpoint%20Guide.pdf) for integration channel but none of registered callbacks are ever called after installation.

But if I add ExternalApplication or ExternalUserInterface, I do get postbackUrl called and embedded iframe, both work flawlessly. 

According to this page https://help.linnworks.com/support/solutions/articles/7000007438-what-is-a-manifest- , it looks like channel integration is not supported anymore. Can you confirm that?

My manifest (replaced real url) in case I missed something. Not all URL's are registered but I would get 404 logged if those were called:

```json
{
  "modules": [
    {
      "type": "ExternalApplication",
      "parameters": [
        {
          "name": "PostbackUrl",
          "value": "https://example.com/app_dev.php/linnworks/postback?token=[{TOKEN}]&tracking=[{TRACKING}]"
        }
      ]
    },
    {
      "path": "",
      "type": "ExternalUserInterface",
      "moduleName": "MyDashboard",
      "formattedName": "My Dashboard",
      "icon": "fa fa-usd",
      "parameters": [
        {
          "name": "URL",
          "value": "https://example.com/app_dev.php/linnworks/embedded/[{TOKEN}]"
        }
      ]
    },
    {
      "type": "ChannelIntegration",
      "parameters": [
        {
          "name": "ChannelName",
          "value": "MYINTEGRATION"
        },
        {
          "name": "ChannelFriendlyName",
          "value": "My integration 3"
        },
        {
          "name": "ChannelLogoURL",
          "value": "https://example.com/images/logo.png"
        },
        {
          "name": "AddNewUserEndpoint",
          "value": "https://example.com/app_dev.php/linnworks/new_user"
        },
        {
          "name": "UserConfigEndpoint",
          "value": "https://example.com/app_dev.php/api/Config/UserConfig"
        },
        {
          "name": "SaveConfigEndpoint",
          "value": "https://example.com/app_dev.php/api/Config/SaveUserConfig"
        },
        {
          "name": "ShippingTagsEndpoint",
          "value": "https://example.com/app_dev.php/api/Config/ShippingTags"
        },
        {
          "name": "PaymentTagsEndpoint",
          "value": "https://example.com/app_dev.php/api/Config/PaymentTags"
        },
        {
          "name": "ConfigDeletedEndpoint",
          "value": "https://example.com/app_dev.php/linnworks/user_deleted"
        },
        {
          "name": "ConfigTestEndpoint",
          "value": "https://example.com/app_dev.php/linnworks/config_test"
        },
        {
          "name": "OrdersEndpoint",
          "value": "https://example.com/app_dev.php/api/Order/Orders"
        },
        {
          "name": "DespatchEndpoint",
          "value": "https://example.com/app_dev.php/api/Order/Despatch"
        },
        {
          "name": "ProductsEndpoint",
          "value": "https://example.com/app_dev.php/api/Product/Products"
        },
        {
          "name": "InventoryUpdateEndpoint",
          "value": "https://example.com/app_dev.php/api/Product/InventoryUpdate"
        },
        {
          "name": "PriceUpdateEndpoint",
          "value": "https://example.com/app_dev.php/api/Product/PriceUpdate"
        },
        {
          "name": "InventoryUpdateBatchSize",
          "value": "1000"
        },
        {
          "name": "DespatchUpdateBatchSize",
          "value": "100"
        },
        {
          "name": "PriceUpdateBatchSize",
          "value": "1000"
        }
      ]
    }
  ]
}
```

**Comment by LinnSystems** [comment]
can you please create a support ticket on help.linnworks.com and I will assist you with this query. Channel integration extension is supported and functioning.

**Comment by wjbLabs** [comment]
Thanks for reply. Anyway, I can't login to help.linnworks.com with same credentials I use on https://linnworks.net/.

When I tried password recovery, got this message (used email is visible but bots can't scrape it): 

![image](https://cloud.githubusercontent.com/assets/1964158/25280384/0e1439b8-26aa-11e7-8367-461e1fa43664.png)

Could that be that because of account itself, channel integration doesn't work?

**Comment by LinnSystems** [comment]
Hello,
Your account profile is set correctly. 

Can you please try to access Support Portal from within Linnworks.net?

![image](https://cloud.githubusercontent.com/assets/12414471/25304357/7fbc3940-275d-11e7-9987-0de0fdec0a3c.png)

**Comment by wjbLabs** [comment]
Sorry for late reply.

Yes, I can login to portal, even have the external application running: 
![image](https://cloud.githubusercontent.com/assets/1964158/25797356/23644836-33dd-11e7-920b-683324391f4d.png)
