### ISSUE TITLE
AuthorizeByApplication

### ISSUE THREAD

**Issue by DanielMiara** [LinnSystems/LinnworksNetSDK#22]
Hello,

(https://apps.linnworks.net/Api/Method/Auth-AuthorizeByApplication)

I need help because the documentation is not clear to me.
I created an application in LW and have **Application ID** and **Secret** as well.
I want to get the token so I’ve sent POST data to 
https://api.linnworks.net/api/Auth/AuthorizeByApplication

CULR --
'Host: api.linnworks.net',
'Connection: keep-alive',
'Accept: application/json, text/javascript, */*; q=0.01',
'Origin: https://www.linnworks.net',
'Accept-Language: en',
'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36',
'Content-Type: application/x-www-form-urlencoded; charset=UTF-8',
'Referer: https://www.linnworks.net/',
'Accept-Encoding: gzip, deflate’,

POST --
    'applicationId' => $ApplicationId,
    'applicationSecret' => $ApplicationSecret,
    'userId' => ‘HOW TO GET IT?'

I’m getting 
string(85) "{"Code":"-","Message":"An internal error occurred. Please contact Linnworks support”}"

**Comment by DanielMiara** [comment]
> 3. On installation, you will receive a token - static parameter that you will have to pass with application Id and Application Secret (both visible in dev portal) to this call http://apps.linnworks.net/Api/Method/Auth-AuthorizeByApplication
Running the 'AuthorizeByApplication' call will then return you the 'API token' as 'Token'.

> 
Thanks for the explanation. Problem is because I can't see any token in my end-user account even if I edit the module.

**Comment by LinnSystems** [comment]
The developer portal also lists all users who have installed an application, along with their "permanent token", which is used in the AuthorizeByApplication call. This is visible in the main "Applications" view when you select an app, in the "Installs" grid at the bottom of the screen.
