### ISSUE TITLE
Cannot get inventory items (/api/Inventory/GetInventoryItems). I'm using Python and requests.

### ISSUE THREAD

**Issue by emihir0** [LinnSystems/LinnworksNetSDK#4]
Hi,

I'm a very newbie 'developer' (can't really call myself a developer... yet?). I can authenticate and I get the session token back which I try to use to get my inventory items, without success.

Note that I tried to get, for example, location info based on location_id and it worked, so I'm not sure what I do wrong in trying to get the inventory items. Here is my code:

[my small (just 100 lines) Linnworks.py script](https://gist.github.com/emihir0/f697978faf6a4fcbc5f3c6879414e920)

I'm sure it's some silly mistake, yet I cannot figure it out. I tried to follow the [API docs](https://apps.linnworks.net/Api/Method/Inventory-GetInventoryItems) as close as possible.

Similarly, is there any easier/better way to fetch the GUIDs for my items? I tried to search the API docs and found that _probably_ the only way is through Inventory.

Edit: 
I see I can fetch item ids info using query: "SELECT pkStockItemID, ItemNumber, ItemTitle FROM StockItem WHERE bLogicalDelete = 0" with [api/Dashboards/ExecuteCustomScriptQuery](https://apps.linnworks.net/Api/Method/Dashboards-ExecuteCustomScriptQuery). However, I would still like to know why my original script does not work :/.

**Comment by LinnSystems** [comment]
Hi emihir0,

We don't usually provide support for programming related questions via Github - You should be able to raise them through your Linnworks Account or you can use something like stackoverflow.com if the question is general.

If you could create a ticket in your account on Linnworks we should be able to take a look into it for you. Please make sure you provide the error that you are receiving and if possible your request too.
