### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by cmunden** [LinnSystems/LinnworksNetSDK#6]
This is not an issue... but just wanted to let you know that I am developing the Linnworks API in the Java language here:  https://github.com/Notronix/JaLAPI

Feel free to contribute or give feedback.

Clint

**Comment by LinnSystems** [comment]
Hi Clint,

Thanks for that - We appreciate your work. 

We'll take a look over it and look at the possibility of including it in our resources in the future. 

As all our code is generated automatically at the moment, it would make sense for us to directly include the Java language generation into it, but this hasn't been completed just yet.
