### ISSUE TITLE
Problems in connecting via SSL and CloudFlare

### ISSUE THREAD

**Issue by Coobers** [LinnSystems/LinnworksNetSDK#9]
Occasionally connection is broken and we receive error The request was aborted: Could not create SSL/TLS secure channel. returned error (4 cases on 190 connections) .

Works fine with direct http connection.
We confirmed that backend didn't receive those requests and problem is in between CloudFlare and Linnworks.

**Comment by Coobers** [comment]
In linnworks.net after connecting sdk.





On Wed, Jan 18, 2017 at 9:52 AM +0100, "Linn Systems" <notifications@github.com> wrote:












Hi @Coobers,


Can you confirm to me where you are receiving the stated issue? Is this an overall issue with the API, with the software itself, or an issue with other services?

**Comment by LinnSystems** [comment]
Hi @Coobers,

This is certainly worrying that you are receiving errors such as this. In order to check this out, would you be able to confirm the calls that you are making.

Furthermore, would you be able to tell me if the request is being dropped by the server or if it is timing out?

**Comment by Coobers** [comment]
Actually linnworks is making those requests that are failing.
We received them via Logs Automation report in linnworks.net

What we know is that Cloudflare did not send us requests.
We followed standard procedure, including connection monitoring (nothing was dropped) and turned on development mode (CF then forwards everything as is).

I can just speculate that it might be connected with way Channel Integration connects to API's.

**Comment by LinnSystems** [comment]
Thanks for confirming.

Would you be able to send us over your logs via our ticketing system? I'd rather us check this out via ticket, as opposed to having your (possibly) sensitive information available through github. 

You can raise a ticket at help.linnworks.com - Just reference this issue.

**Comment by LinnSystems** [comment]
This issue is now being closed as we have not had a reply in a sufficient time. Please, if you do want to re-raise this issue, contact us through our help centre as mentioned above.
